name: dart_starter
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  nitric_sdk: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
